name: flutter_leofortune2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  toast:
  http:
  intl:
  flutter_slidable:
  font_awesome_flutter:
  provider:
  flutter_launcher_icons:
  flutter_native_splash:
  flutter_riverpod:

  freezed_annotation:
  json_annotation:

  syncfusion_flutter_charts:

  scrollable_positioned_list:
  uuid:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner:
  freezed:
  json_serializable:

flutter:

  uses-material-design: true

  assets:
    - assets/image/

flutter_native_splash:
  image: "assets/image/ic_launcher.png"
  color: "1C305A"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/ic_launcher.png"

adaptive_icon_background: "#1C305A"
adaptive_icon_foreground: "assets/image/ic_launcher.png"
